// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tienda_Streaming.Data;

#nullable disable

namespace Tienda_Streaming.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tienda_Streaming.Models.Account.PasswordResetToken", b =>
                {
                    b.Property<int>("Id_PasswordResetToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_PasswordResetToken"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_Expiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Uso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<string>("Ip_Solicitud")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id_PasswordResetToken");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("Id_Usuario", "Fecha_Expiracion");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Auditoria", b =>
                {
                    b.Property<int>("Id_Auditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Auditoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Formulario")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Metodo_Ejecutado")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Auditoria");

                    b.HasIndex("Id_Usuario_Creacion");

                    b.HasIndex("Id_Usuario_Modifica");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.BilleteraVendedores", b =>
                {
                    b.Property<int>("Id_Billetera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Billetera"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric(12,2)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Billetera");

                    b.HasIndex("Id_Usuario")
                        .IsUnique();

                    b.ToTable("BilleteraVendedores");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.CodigosCompra", b =>
                {
                    b.Property<int>("Id_Codigo_Compra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Codigo_Compra"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Correo_Cliente")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Expiracion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Nombre_Cliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Saldo_Disponible")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Valor_Inicial")
                        .HasColumnType("numeric(12,2)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Codigo_Compra");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CodigosCompra");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.ComboPlataformas", b =>
                {
                    b.Property<int>("Id_Combo_Plataforma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Combo_Plataforma"));

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Id_Combo")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Plataforma")
                        .HasColumnType("integer");

                    b.HasKey("Id_Combo_Plataforma");

                    b.HasIndex("Id_Plataforma");

                    b.HasIndex("Id_Combo", "Id_Plataforma")
                        .IsUnique();

                    b.ToTable("ComboPlataformas");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Combos", b =>
                {
                    b.Property<int>("Id_Combo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Combo"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Tipo_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Tiempo_Pantalla")
                        .HasColumnType("integer");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Combo");

                    b.HasIndex("Id_Tipo_Usuario");

                    b.HasIndex("Nombre", "Id_Tipo_Usuario", "Tiempo_Pantalla")
                        .IsUnique();

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.CorreosPlataforma", b =>
                {
                    b.Property<int>("Id_Correo_Plataforma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Correo_Plataforma"));

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Cuerpo_Html")
                        .HasColumnType("text");

                    b.Property<string>("Cuerpo_Texto")
                        .HasColumnType("text");

                    b.Property<string>("Destinatarios")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Encabezados")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Recepcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hash_Mensaje")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Remitente")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Texto_Busqueda")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Correo_Plataforma");

                    b.HasIndex("Fecha_Recepcion");

                    b.HasIndex("Hash_Mensaje")
                        .IsUnique();

                    b.ToTable("CorreosPlataforma");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Cuentas", b =>
                {
                    b.Property<int>("Id_Cuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Cuenta"));

                    b.Property<string>("Contrasena_Cuenta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Contraseña_Cuenta");

                    b.Property<string>("Correo_Cuenta")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Vencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Plataforma")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Tipo_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Perfil_Cuenta")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Pin_Cuenta")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Tiempo_Pantalla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30);

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Cuenta");

                    b.HasIndex("Id_Tipo_Usuario");

                    b.HasIndex("Id_Plataforma", "Id_Tipo_Usuario", "Vigente");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Dominios", b =>
                {
                    b.Property<int>("Id_Dominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Dominio"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DominioPadre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("No");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Padre")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Crea")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Dominio");

                    b.HasIndex("Id_Padre");

                    b.ToTable("Dominios");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.ImagenesProducto", b =>
                {
                    b.Property<int>("Id_ImagenProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_ImagenProducto"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Plataforma")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Tipo_Imagen")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<int>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_ImagenProducto");

                    b.HasIndex("Id_Tipo_Imagen");

                    b.HasIndex("Orden");

                    b.HasIndex("Id_Plataforma", "Id_Tipo_Imagen")
                        .IsUnique();

                    b.ToTable("ImagenesProducto");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.InicioContenido", b =>
                {
                    b.Property<int>("Id_InicioContenido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_InicioContenido"));

                    b.Property<string>("Contenido")
                        .HasColumnType("text");

                    b.Property<string>("EnlaceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<short>("MostrarEnInicio")
                        .HasColumnType("smallint");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Resumen")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TextoBoton")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TipoContenido")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_InicioContenido");

                    b.HasIndex("TipoContenido", "Orden");

                    b.ToTable("InicioContenidos");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Menus", b =>
                {
                    b.Property<int>("Id_Menu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Menu"));

                    b.Property<string>("Controlador")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icono")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("Id_Padre")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.Property<string>("Vista")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id_Menu");

                    b.HasIndex("Id_Padre");

                    b.HasIndex("Controlador", "Vista");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.MovimientosBilletera", b =>
                {
                    b.Property<int>("Id_Movimiento_Billetera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Movimiento_Billetera"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Billetera")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Pedido")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<decimal>("Saldo_Anterior")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Saldo_Nuevo")
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("Tipo_Movimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id_Movimiento_Billetera");

                    b.HasIndex("Id_Billetera");

                    b.HasIndex("Id_Pedido");

                    b.ToTable("MovimientosBilletera");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.PedidoCuentas", b =>
                {
                    b.Property<int>("Id_Pedido_Cuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Pedido_Cuenta"));

                    b.Property<int>("Id_Cuenta")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Pedido")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Pedido_Detalle")
                        .HasColumnType("integer");

                    b.HasKey("Id_Pedido_Cuenta");

                    b.HasIndex("Id_Cuenta");

                    b.HasIndex("Id_Pedido_Detalle");

                    b.HasIndex("Id_Pedido", "Id_Cuenta")
                        .IsUnique();

                    b.ToTable("PedidoCuentas");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.PedidoDetalles", b =>
                {
                    b.Property<int>("Id_Pedido_Detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Pedido_Detalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Combo")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Pedido")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Plataforma")
                        .HasColumnType("integer");

                    b.Property<decimal>("Precio_Unitario")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Tiempo_Pantalla")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo_Producto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id_Pedido_Detalle");

                    b.HasIndex("Id_Combo");

                    b.HasIndex("Id_Pedido");

                    b.HasIndex("Id_Plataforma");

                    b.ToTable("PedidoDetalles");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Pedidos", b =>
                {
                    b.Property<int>("Id_Pedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Pedido"));

                    b.Property<string>("Correo_Cliente")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("Fecha_Compra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Codigo_Compra")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Tipo_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre_Cliente")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(12,2)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Pedido");

                    b.HasIndex("Id_Codigo_Compra");

                    b.HasIndex("Id_Tipo_Usuario");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Permisos", b =>
                {
                    b.Property<int>("Id_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Permiso"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CodigoPermiso")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Controlador")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HttpMetodo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Id_Menu")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Metodo")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TipoPermiso")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Menu");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Permiso");

                    b.HasIndex("CodigoPermiso")
                        .IsUnique()
                        .HasFilter("\"CodigoPermiso\" IS NOT NULL");

                    b.HasIndex("Id_Menu");

                    b.HasIndex("TipoPermiso", "Id_Menu", "Accion")
                        .IsUnique()
                        .HasFilter("\"Id_Menu\" IS NOT NULL AND \"TipoPermiso\" = 'Menu'");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.PreciosProducto", b =>
                {
                    b.Property<int>("Id_Precio_Producto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Precio_Producto"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Plataforma")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Tipo_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Tiempo_Pantalla")
                        .HasColumnType("integer");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Precio_Producto");

                    b.HasIndex("Id_Tipo_Usuario");

                    b.HasIndex("Id_Plataforma", "Id_Tipo_Usuario", "Tiempo_Pantalla")
                        .IsUnique();

                    b.ToTable("PreciosProducto");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Roles", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rol"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Rol");

                    b.HasIndex("Rol")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Roles_Permisos", b =>
                {
                    b.Property<int>("Id_Rol_Permiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rol_Permiso"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Permiso")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Rol_Permiso");

                    b.HasIndex("Id_Permiso");

                    b.HasIndex("Id_Rol", "Id_Permiso")
                        .IsUnique();

                    b.ToTable("Roles_Permisos");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Roles_User", b =>
                {
                    b.Property<int>("Id_Roles_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Roles_User"));

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Roles_User");

                    b.HasIndex("Id_Rol");

                    b.HasIndex("Id_Usuario", "Id_Rol")
                        .IsUnique();

                    b.ToTable("Roles_User");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.SistemaVisualConfig", b =>
                {
                    b.Property<int>("Id_SistemaVisualConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_SistemaVisualConfig"));

                    b.Property<string>("FaviconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("LoginBackgroundUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_SistemaVisualConfig");

                    b.ToTable("SistemaVisualConfig");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Usuarios", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Usuario"));

                    b.Property<short>("Debe_Cambiar_Password")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0);

                    b.Property<string>("E_Mail")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTime>("Fecha_Creacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Fecha_Modifica")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Id_Usuario_Creacion")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Usuario_Modifica")
                        .HasColumnType("integer");

                    b.Property<string>("Maquina_Creacion")
                        .HasColumnType("text");

                    b.Property<string>("Maquina_Modifica")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<short>("Vigente")
                        .HasColumnType("smallint");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("E_Mail")
                        .IsUnique();

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Account.PasswordResetToken", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Usuarios", null)
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Auditoria", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Usuarios", "UsuarioCrea")
                        .WithMany()
                        .HasForeignKey("Id_Usuario_Creacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tienda_Streaming.Models.Administracion.Usuarios", "UsuarioModifica")
                        .WithMany()
                        .HasForeignKey("Id_Usuario_Modifica")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UsuarioCrea");

                    b.Navigation("UsuarioModifica");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.BilleteraVendedores", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.ComboPlataformas", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Combos", "Combo")
                        .WithMany("Plataformas")
                        .HasForeignKey("Id_Combo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "Plataforma")
                        .WithMany()
                        .HasForeignKey("Id_Plataforma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Combo");

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Combos", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("Id_Tipo_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Cuentas", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "Plataforma")
                        .WithMany()
                        .HasForeignKey("Id_Plataforma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("Id_Tipo_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plataforma");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Dominios", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "Padre")
                        .WithMany()
                        .HasForeignKey("Id_Padre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.ImagenesProducto", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "Plataforma")
                        .WithMany()
                        .HasForeignKey("Id_Plataforma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "TipoImagen")
                        .WithMany()
                        .HasForeignKey("Id_Tipo_Imagen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Plataforma");

                    b.Navigation("TipoImagen");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Menus", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Menus", "Padre")
                        .WithMany()
                        .HasForeignKey("Id_Padre")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.MovimientosBilletera", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.BilleteraVendedores", "Billetera")
                        .WithMany()
                        .HasForeignKey("Id_Billetera")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.Pedidos", "Pedido")
                        .WithMany()
                        .HasForeignKey("Id_Pedido")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Billetera");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.PedidoCuentas", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Cuentas", "Cuenta")
                        .WithMany()
                        .HasForeignKey("Id_Cuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.Pedidos", "Pedido")
                        .WithMany("Cuentas")
                        .HasForeignKey("Id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.PedidoDetalles", "PedidoDetalle")
                        .WithMany()
                        .HasForeignKey("Id_Pedido_Detalle")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cuenta");

                    b.Navigation("Pedido");

                    b.Navigation("PedidoDetalle");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.PedidoDetalles", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Combos", "Combo")
                        .WithMany()
                        .HasForeignKey("Id_Combo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tienda_Streaming.Models.Administracion.Pedidos", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("Id_Pedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "Plataforma")
                        .WithMany()
                        .HasForeignKey("Id_Plataforma")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Combo");

                    b.Navigation("Pedido");

                    b.Navigation("Plataforma");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Pedidos", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.CodigosCompra", "CodigoCompra")
                        .WithMany()
                        .HasForeignKey("Id_Codigo_Compra")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("Id_Tipo_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CodigoCompra");

                    b.Navigation("TipoUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Permisos", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Menus", "Menu")
                        .WithMany()
                        .HasForeignKey("Id_Menu")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.PreciosProducto", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "Plataforma")
                        .WithMany()
                        .HasForeignKey("Id_Plataforma")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.Dominios", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("Id_Tipo_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plataforma");

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Roles_Permisos", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Permisos", "Permiso")
                        .WithMany()
                        .HasForeignKey("Id_Permiso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Roles_User", b =>
                {
                    b.HasOne("Tienda_Streaming.Models.Administracion.Roles", "Rol")
                        .WithMany()
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tienda_Streaming.Models.Administracion.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Combos", b =>
                {
                    b.Navigation("Plataformas");
                });

            modelBuilder.Entity("Tienda_Streaming.Models.Administracion.Pedidos", b =>
                {
                    b.Navigation("Cuentas");

                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}

